steps:
  - id: 'tf-init'
    name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args: 
    - '-c'
    - | 
        terraform init 
  # - timeout: "600s"

  - id: 'tf-plan'
    name: 'hashicorp/terraform:latest'
    waitFor: 
    - 'tf-init'
    entrypoint: 'sh'
    args:
      - "-c"
      - 'pwd'
      - 'ls -la'
      - |
          terraform plan
  # - timeout: "600s"

 

  - id: 'tf-apply'
    name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - "-c"
      - |
          terraform apply -auto-approve
  # - timeout: "600s"


options:
  logging: CLOUD_LOGGING_ONLY
